""" disconnection table """

disconnection_table = {
    'Li': ['N', 'O', 'F', 'Cl', 'Br'],
    'Be': ['O', 'F'],
    'Na': ['N', 'O', 'F', 'Cl', 'Br', 'I'],
    'Mg': ['N', 'O', 'F', 'Cl'],
    'Al': ['O', 'F'],
    'K': ['C', 'N', 'O', 'F', 'S', 'Cl', 'Se', 'Br', 'I'], # removed entry for 'Au' since all metal-metal bonds should be preserved
    'Ca': ['N', 'O', 'F', 'Cl', 'Br'],
    'Sc': ['O', 'F', 'Cl'],
    'Ti': ['O', 'F'],
    'V': ['O', 'F'],
    'Cr': ['O', 'F'],
    'Mn': ['O', 'F'],
    'Fe': ['F'],
    'Co': ['F'],
    'Ni': ['F'],
    'Cu': ['F'],
    'Zn': ['O', 'F'],
    'Ga': ['F'],
    'Rb': ['C', 'N', 'O', 'F', 'S', 'Cl', 'Se', 'Br', 'I'],  # removed entry for 'Au' since all metal-metal bonds should be preserved
    'Sr': ['N', 'O', 'F', 'Cl', 'Br', 'I'],
    'Y': ['N', 'O', 'F', 'Cl', 'Br'],
    'Zr': ['N', 'O', 'F'],
    'Nb': ['O', 'F'],
    'Mo': ['F'],
    'Tc': ['F'],
    'Ru': ['F'],
    'Pd': ['F'],
    'Ag': ['F'],
    'Cd': ['O', 'F'],
    'In': ['F'],
    'Sn': ['F'],
    'Sb': ['F'],
    'Cs': ['C', 'N', 'O', 'F', 'S', 'Cl', 'Se', 'Br', 'I'],  # removed entry for 'Au' since all metal-metal bonds should be preserved
    'Ba': ['N', 'O', 'F', 'Cl', 'Br', 'I'],
    'La': ['N', 'O', 'F', 'Cl', 'Br'],
    'Ce': ['N', 'O', 'F', 'Cl', 'Br'],
    'Pr': ['N', 'O', 'F', 'Cl', 'Br'],
    'Nd': ['N', 'O', 'F', 'Cl', 'Br'],
    'Pm': ['N', 'O', 'F', 'Cl', 'Br'],
    'Sm': ['N', 'O', 'F', 'Cl', 'Br'],
    'Eu': ['N', 'O', 'F', 'Cl', 'Br'],
    'Gd': ['N', 'O', 'F', 'Cl', 'Br'],
    'Tb': ['N', 'O', 'F', 'Cl', 'Br'],
    'Dy': ['N', 'O', 'F', 'Cl', 'Br'],
    'Ho': ['N', 'O', 'F', 'Cl', 'Br'],
    'Er': ['N', 'O', 'F', 'Cl', 'Br'],
    'Tm': ['N', 'O', 'F', 'Cl', 'Br'],
    'Yb': ['N', 'O', 'F', 'Cl', 'Br'],
    'Lu': ['N', 'O', 'F', 'Cl'],
    'Hf': ['N', 'O', 'F', 'Cl'],
    'Ta': ['O', 'F'],
    'Re': ['F'],
    'Os': ['F'],
    'Ir': ['F'],
    'Au': ['K', 'Rb', 'Cs', 'Fr'],
    'Hg': ['F'],
    'Tl': ['F'],
    'Bi': ['F'],
    'Po': ['F'],
    'Fr': ['C', 'N', 'O', 'F', 'S', 'Cl', 'Se', 'Br', 'I'],  # removed entry for 'Au' since all metal-metal bonds should be preserved
    'Ra': ['N', 'O', 'F', 'Cl', 'Br', 'I'],
    'Ac': ['N', 'O', 'F', 'Cl', 'Br'],
    'Th': ['N', 'O', 'F', 'Cl'],
    'Pa': ['O', 'F'],
    'U': ['O', 'F', 'Cl'],
    'Np': ['O', 'F', 'Cl'],
    'Pu': ['N', 'O', 'F', 'Cl'],
    'Am': ['N', 'O', 'F', 'Cl'],
    'Cm': ['N', 'O', 'F', 'Cl'],
    'Bk': ['N', 'O', 'F', 'Cl'],
    'Cf': ['N', 'O', 'F', 'Cl'],
    'Es': ['N', 'O', 'F', 'Cl'],
    'Fm': ['N', 'O', 'F', 'Cl'],
    'Md': ['N', 'O', 'F', 'Cl'],
    'No': ['N', 'O', 'F', 'Cl']
} # no values for lawrencium to oganesson
